version: "3.3"

services:

  app:
    build: 
      context: ./ecommerce-app
      dockerfile: ./docker/app/Dockerfile
    image: ecommerce-app
    environment:
      FLASK_ENV: "development"
      FLASK_APP: "src/app.py"
      MONGO_URI: "mongodb://mongo:27017/ecommerce"
    ports:
      - "5000:5000"
    volumes: 
      - ./ecommerce-app/src:/app/src
    depends_on:
      - mongo
    
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongo:/data/db

  mongo-seed:
    build: 
      context: ./ecommerce-app/docker/mongo-seed
      dockerfile: ./Dockerfile
    links:
      - mongo
